// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace CreateEnvelopes
{
    public class CreateEnvelopesOutputs: SystemResults
    {
		/// <summary>
		/// The total area of the Conceptual Masses
		/// </summary>
		[JsonProperty("Total Area")]
		public double TotalArea { get; set; }

        /// <summary>
        /// Construct a CreateEnvelopesOutputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public CreateEnvelopesOutputs() : base()
        {
        }

        /// <summary>
        /// Construct a CreateEnvelopesOutputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public CreateEnvelopesOutputs(double totalArea) : base()
        {
			this.TotalArea = totalArea;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}